### ISSUE TITLE
Linking error while compiling crate

### ISSUE THREAD

**Issue by pmeier** [conda-forge/rust-feedstock#148] opened 2023-06-01 11:18 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```bash
$ cargo install cargo-upgrades
[...]
error: linking with `/home/philip/.conda/envs/rustcq/bin/x86_64-conda-linux-gnu-cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/philip/.conda/envs/rustcq/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/philip/.conda/envs/rustcq/bin:/opt/miniconda3/condabin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/home/philip/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin" VSLANG="1033" "/home/philip/.conda/envs/rustcq/bin/x86_64-conda-linux-gnu-cc" "-m64" "/tmp/rustcYW7UPb/symbols.o" "/tmp/cargo-installBvtTX9/release/deps/cargo_upgrades-ab896adf27a2eb31.cargo_upgrades.a4b5e9e2-cgu.5.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installBvtTX9/release/deps" "-L" "/usr/lib" "-L" "/home/philip/.conda/envs/rustcq/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/philip/.conda/envs/rustcq/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-957b4aff41f8cd46.rlib" "-Wl,-Bdynamic" "-lgit2" "-lssl" "-lcrypto" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/philip/.conda/envs/rustcq/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installBvtTX9/release/deps/cargo_upgrades-ab896adf27a2eb31" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs"
  = note: /home/philip/.conda/envs/rustcq/bin/../lib/gcc/x86_64-conda-linux-gnu/12.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libhttp_parser.so.2.9, needed by /usr/lib/libgit2.so, not found (try using -rpath or -rpath-link)
[...]
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `cargo-upgrades` due to previous error
error: failed to compile `cargo-upgrades v1.3.7`, intermediate artifacts can be found at `/tmp/cargo-installBvtTX9`
```

Same command works fine with my system `cargo`.

### Installed packages

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
gcc_impl_linux-64         12.2.0              hcc96c02_19    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libgcc-devel_linux-64     12.2.0              h3b97bd3_19    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libsanitizer              12.2.0              h46fd767_19    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
rust                      1.69.0               h70c747d_4    conda-forge
rust-std-x86_64-unknown-linux-gnu 1.69.0               hc1431ca_4    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
```

Created with `conda create -n rustcq -c conda-forge rust`

### Environment info

```shell
active environment : rustcq
    active env location : /home/philip/.conda/envs/rustcq
            shell level : 1
       user config file : /home/philip/.condarc
 populated config files : /home/philip/.condarc
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.37=0
                          __linux=6.3.4=0
                          __unix=0=0
       base environment : /opt/miniconda3  (read only)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/philip/.conda/pkgs
       envs directories : /home/philip/.conda/envs
                          /opt/miniconda3/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.8 Linux/6.3.4-arch2-1 arch/rolling glibc/2.37
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by pmeier** [comment] 2023-06-01 13:12
Thinking about this more, I'm not sure if this is in scope for this feedstock. Does a crate have any notion about the C library it wraps?

**Comment by pkgw** [comment] 2023-06-01 17:38
Since the error seems to relate to a system shared library dependency (`/usr/lib/libgit2.so`) not having *its* dependencies satisfied, I would doubt that the error is specifically due to the conda-forge Rust package. That library file should have embedded information suitable for the linker to find all of its dependencies, regardless of the toolchain that's being used. It might be that when you're building with a local copy of Cargo, the system toolchain has some different settings that allow the build to succeed as a matter of luck, but I wouldn't expect this to represent something that could be fixed in this package.

Did you install that `libgit2` manually? I think you might need to remove it and/or reinstall it. The output of `ldd /usr/lib/libgit2.so` might be helpful here.

**Comment by pkgw** [comment] 2023-08-26 23:49
OK, coming back to revisit this, I think that this issue is understandable in the context of the conda-forge Rust toolchain, but is not something that we can fix.

I think the basic problem in your setup is that conda-forge's Linux compiler toolchains are self-contained: they don't reference standard system directories like `/lib` or `/usr/lib` at all when linking. So, generally, if you're using the conda-forge compilers to compile a piece of code that depends on some third-party library, even if there happens to be a copy of that library in `/usr/lib`, it won't get used.

In your particular case, it seems that `git2-rs` is relying on a non-vendored version of `libgit2`, which [it detects using `pkg-config`](https://github.com/rust-lang/git2-rs/blob/master/libgit2-sys/build.rs#L8). It looks like your environment doesn't contain a conda-forge version of `pkg-config,` so the build process will use the system version of that tool, which in turn will basically say that Rust can link with `libgit2` using arguments along the lines of `-L/usr/lib -lgit2`.

Normally that would be fine, but because we're using conda-forge's compilers, there's a limitation. The `-L` argument registers a path for the compiler/linker to search for libraries that are specified in `-l` arguments ... but that search path does *not* apply to the other shared libraries that those libraries may depend on.  In order to find those, the linker searches using the shared library "rpath" list. A directory like `/usr/lib` is built-in to the linker's rpath list for the system compilers, but not conda-forge's. So even though the `-L` argument allows the conda-forge linker to find `libgit2.so`, it doesn't allow it to find the dependent `libhttp_parser.so` even though it lives in the same directory! As remarked in the original error message, to add this path you'd need to include an additional `-rpath` or `-rpath-link` argument.

You could probably hack in such an argument, but it would be a bit of a fragile solution at best, because bad things would easily happen if both the conda-forge prefix and `/usr/lib` contained incompatible versions of the same shared library. (Such as, say, `libc`.)

In this *particular* case, probably the easiest solution is to get git2-rs to "vendor" libgit2 and compile its own version. You could potentially to that by uninstalling your system version of libgit2, or it looks like turning on the `zlib-ng-compat` feature would also force this. Installing `pkg-config` inside your conda-forge prefix might also make this happen since it should only report libraries that are provided in the conda-forge prefix (it is self-contained in the same way as the toolchain).

The broader situation is that if you are trying to use conda-forge tools to build a binary, *all* of its library dependencies really need to be built and installed within the conda-forge environment. Trying to link to system-provided shared libraries might work in some cases, but this is an example of how such intermixing can quickly fall apart.

Hopefully that helps! I'm going to close this issue since, as I wrote above, we can't fix this issue — the self-containment of the toolchains is both the root cause of what you're seeing and a fundamental aspect of the conda-forge compiler setup. But if you have any questions we should be able to keep commenting.

**Closed by pkgw** 2023-08-26 23:49 UTC
Labels: bug
